Added delete shoe feature
dgazzola/sneaker-stars pull request #15
Opened 2023-02-08 21:12 UTC by JusLafo

- Added a column called "is_admin" which is a boolean
- Added a button on the shoeShowPage that only shows when someone has an admin status of true
- Added functionality of a delete button to delete the specified shoe

2023-02-08 21:13 UTC, dgazzola commented on client/src/components/ShoeShowPage.js
>          try{
space after try

2023-02-08 21:17 UTC, dgazzola reviewed
looks dope, just a couple spacing things

2023-02-08 21:17 UTC, dgazzola commented on client/src/components/ShoeShowPage.js
>          }   catch(err) {
theres a double space before catch

2023-02-08 21:17 UTC, dgazzola commented on client/src/components/ShoeShowPage.js
>          getShoe()
not 100% but this might be double indented

2023-02-08 21:17 UTC, dgazzola commented on client/src/components/ShoeShowPage.js
>      return(
think space before parenths

2023-02-08 21:17 UTC, dgazzola commented on client/src/components/UserShowPage.js
> +          if(!response.ok) {
space after if

2023-02-08 21:17 UTC, dgazzola commented on client/src/components/UserShowPage.js
>                <h1>{user.username}'s Profile</h1>
I think this chunk of child elements is double indented

2023-02-09 16:31 UTC, nwalberts requested changes

2023-02-09 16:31 UTC, nwalberts commented on client/src/components/App.js
> +            (props) => <ShoeShowPage {...props} user={currentUser}/>}
indentation is off. 
```
<Route 
     props
/>
```

2023-02-09 16:31 UTC, nwalberts commented on client/src/components/ShoeShowPage.js
> +      alert("Delete Cancelled")
I would probably say "Your shoe has not been deleted."

2023-02-09 16:31 UTC, nwalberts commented on client/src/components/ShoeShowPage.js
>          </div>
this p tag can be written on one line
this div can be written on one line

2023-02-09 16:31 UTC, nwalberts commented on client/src/components/ShoeShowPage.js
> +      <div>
this div isnt doing anything, lets delete it

2023-02-09 16:31 UTC, nwalberts commented on client/src/components/UserShowPage.js
> +  })
probably dont need all of these properties on this default state, and it looks a bit wild. remove

2023-02-09 16:31 UTC, nwalberts commented on client/src/components/UserShowPage.js
> +      <div>
this div isnt doing anything. remove it and/or replace it with a React fragment

2023-02-09 16:31 UTC, nwalberts commented on client/src/components/UserShowPage.js
> +      <div>
both of these divs arent doing anything. replace the outer one with a react fragment, and nuke the inner one

2023-02-09 16:31 UTC, nwalberts commented on server/src/routes/api/v1/shoesRouter.js
> +    const deletedShoe = await Shoe.query().findOne("name", body.name).delete()
lets use `deleteById` instead. its faster!

2023-02-09 18:44 UTC, merged